# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d732ce6a5d37418fcb6dbd183d2f52ae18a398f1f7f6e40de0761fbb9608159211737b10cbbdfa2bce38153bf182364c0993de4c2c47dc2dd78c3bab7c1f5c55

test:
  secret_key_base: 95ec0293a022362940bb3903e2b22009fe12de8ed9bfaf77458dbdd66acc41fe6b655d26d793ca96f01e9355a51f18ddf93be468530ad44f35c9e007e3fcfb78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
